FROM balenalib/%%RESIN_MACHINE_NAME%%-debian:stretch

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update && apt-get install -qy \
    device-tree-compiler \
    iperf3 \
    iw \
    wireless-tools

WORKDIR /usr/src/app

COPY start.sh .

CMD ["start.sh"]
